config/routes.rb
Rails.application.routes.draw do
  get "password_resets/new"
  get "password_resets/edit"
  get "password_resets/create"
  get "password_resets/update"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :products
  get "demo_partials/new"
  get "demo_partials/edit"
  root "static_pages#home"
  get "static_pages/home"
  get "static_pages/help"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users, only: %i(new create show edit update index destroy)
  resources :account_activations, only: %i(edit)
  resources :password_resets, only: %i(new create edit update)

  resources :microposts, only: %i(create destroy)
  resources :relationships, only: %i(create destroy)

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("views.title"), "#", id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("views.home"), root_path %></li>
        <li><%= link_to t("views.help"), "#" %></li>
        <% if logged_in? %>
          <li><%= link_to t("views.user"), users_path %></li>
          <li class="dropdown">
            <%= link_to "#", {class: "dropdown-toggle", "data-toggle" => "dropdown"} do %>
              <%= t("views.account") %>
              <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t("views.profile"), current_user %></li>
              <li><%= link_to t("views.setting"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li> <%= link_to t("views.logout"), logout_path, data: { turbo_method: :delete } %></li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to t("views.login"), login_path %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>